name: Merge Branch

on:
  push:
    branches: [ imgbot ]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/advanced-java'
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'
